#!/usr/bin/env python

import os, sys
from gi.repository import Gio

plugins = Gio.Settings.new('org.gnome.shell')['enabled-extensions']
shellshape = 'shellshape@gfxmonk.net'
if shellshape not in plugins:
	print >> sys.stderr, "Note: appending shellshape to the list of enabled plugins automatically"
	plugins.append(shellshape)

launch_cmd = ['0launch'] + sys.argv[1:]
os.execvp('0launch', launch_cmd)
