#!/usr/bin/env python

import os, sys
from gi.repository import Gio

settings = Gio.Settings.new('org.gnome.shell')
enabled_extensions = 'enabled-extensions'
plugins = settings[enabled_extensions]
shellshape = 'shellshape@gfxmonk.net'
if shellshape not in plugins:
	print >> sys.stderr, "Note: appending shellshape to the list of enabled plugins automatically"
	plugins.append(shellshape)
	# would be much better if we could append to a list atomically here:
	settings[enabled_extensions] = plugins

launch_cmd = ['0launch',
	'http://gfxmonk.net/dist/0install/zeroinstall-plugin-manager.xml',
	'http://gfxmonk.net/dist/0install/gnome-shell.xml',
	'--plugin-command', 'run'] + sys.argv[1:]
os.execvp('0launch', launch_cmd)
