#!/bin/bash
set -eu
. gup/common.sh
gup -u _sources ../tools/tsc
sources="$(cat _sources)"
gup -u $sources
base="$(basename "$2" .js)"
./gup/check-anonymous-functions.py $sources
gup -u ../tools/tsc
../tools/tsc ../src/"$base".ts --out "$1"

