#!bash -eu
. gup/common.sh
gup -u _sources
sources="$(cat _sources)"
gup -u $sources
base="$(basename "$2" .js)"
# ./gup/check-anonymous-functions.py $sources
../node_modules/.bin/tsc ../src/"$base".ts --out "$1"

